### ISSUE TITLE
Indexer resolver stats

### ISSUE THREAD

**Issue by vikiival** [kodadot/loligo#60]
- [x] kodadot/nft-gallery#571
- [x] kodadot/nft-gallery#678
- [x] kodadot/nft-gallery#827
- [ ] kodadot/nft-gallery#877
- [x] kodadot/nft-gallery#878
- [x] kodadot/nft-gallery#898
- [ ] kodadot/nft-gallery#1285
- [x] kodadot/nft-gallery#1496
